version: '3'
services:
    nginx:
        volumes:
            - "./:/app:delegated"
            - "./.docker/nginx.conf:/etc/nginx/conf.d/default.template"
        ports:
          - "80:80"
          - "443:443"
        command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    php:
        environment:
            - COMPOSER_CACHE_DIR=/cache/composer
        volumes:
            - "./:/app"
            - "${COMPOSER_HOME_DIR}/cache/composer:/cache/composer"
        links:
            - mysql
    mysql:
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - "3306:3306"
    node:
        volumes:
            - "./:/app:delegated"
        ports:
            - "3000:3000"
            - "3001:3001"
            - "8080:8080"
        links:
            - nginx
        command: /bin/sh -c ${NPM_START_COMMAND}
volumes:
    mysql-volume: