FROM nginx:stable-alpine
USER root

RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
RUN apk add openssl shadow --update --upgrade --no-cache

RUN set -x ; \
  addgroup -g 1000 -S www-data ; \
  adduser -u 1000 -D -S -G www-data www-data && exit 0 ; exit 1

RUN mkdir -p /app/public/uploads

WORKDIR /app

COPY ./.docker/nginx.conf /etc/nginx/conf.d/default.template
COPY ./.docker/performance /etc/nginx/performance
COPY ./public /app/public

RUN chown -R www-data:www-data /app
RUN chmod -R a+rw /app/public/uploads

RUN ln -sf /app/storage/app /app/public/storage

CMD ["nginx", "-g", "daemon off;"]